POST http://localhost:3333/subscriptions
Content-Type: application/json

// em "error" no send request aparece unsupported media type
// precisamos informarque está enviando no formato JSON para REST API

// em questão de validação

{
    "name": "Erik Hideyuki",
    "email": "erikseki@hotmail.com"
}

### 


GET http://localhost:3333/invites/erik123

###

GET http://localhost:3333/subscribers/erik123/ranking/clicks